"""One-shot script that builds the starter notebooks.

Run from repo root:
    python scripts/build_notebooks.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
NB_DIR = REPO / "notebooks"
NB_DIR.mkdir(exist_ok=True)


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines: tuple[str, ...]) -> list[str]:
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]]


def nb(cells: list[dict], *, accelerator: str | None = None) -> dict:
    """Build a notebook. If `accelerator` is given, embed it in the Kaggle
    notebook metadata block so a `kaggle kernels push` allocates that GPU type
    (the CLI's `kernel-metadata.json` doesn't expose this field; the .ipynb
    metadata does)."""
    meta: dict = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13"},
    }
    if accelerator is not None:
        meta["kaggle"] = {
            "accelerator": accelerator,
            "isGpuEnabled": True,
            "isInternetEnabled": True,
            "language": "python",
            "sourceType": "notebook",
        }
    return {
        "cells": cells,
        "metadata": meta,
        "nbformat": 4,
        "nbformat_minor": 5,
    }


# -----------------------------------------------------------------------------
# 01_eda.ipynb
# -----------------------------------------------------------------------------
eda = nb([
    md(
        "# 01 · EDA — Alice's Wonderland reasoning puzzles",
        "",
        "Confirm the six puzzle categories, look at length distributions, sample a few",
        "puzzles per category to see what the model is expected to do.",
    ),
    code(
        "import sys, pathlib",
        "ROOT = pathlib.Path.cwd().parent if pathlib.Path.cwd().name == 'notebooks' else pathlib.Path.cwd()",
        "sys.path.insert(0, str(ROOT))",
        "",
        "import polars as pl",
        "from src.data import load_train, load_test",
        "",
        "train = load_train()",
        "test = load_test()",
        "print('train shape:', train.shape)",
        "print('test shape :', test.shape)",
        "train.head(3)",
    ),
    md("## Category distribution"),
    code(
        "train.group_by('category').agg(pl.len().alias('count')).sort('count', descending=True)",
    ),
    md("## Prompt and answer length distributions"),
    code(
        "stats = train.with_columns([",
        "    pl.col('prompt').str.len_chars().alias('prompt_chars'),",
        "    pl.col('answer').str.len_chars().alias('answer_chars'),",
        "])",
        "",
        "stats.group_by('category').agg([",
        "    pl.col('prompt_chars').mean().round(0).alias('prompt_mean'),",
        "    pl.col('prompt_chars').max().alias('prompt_max'),",
        "    pl.col('answer_chars').mean().round(1).alias('answer_mean'),",
        "    pl.col('answer_chars').min().alias('answer_min'),",
        "    pl.col('answer_chars').max().alias('answer_max'),",
        "]).sort('category')",
    ),
    md("## One sample per category"),
    code(
        "for cat in sorted(train['category'].unique()):",
        "    row = train.filter(pl.col('category') == cat).head(1).to_dicts()[0]",
        "    print('=' * 80)",
        "    print(f'CATEGORY: {cat}   id={row[\"id\"]}')",
        "    print('=' * 80)",
        "    print(row['prompt'])",
        "    print()",
        "    print(f'ANSWER: {row[\"answer\"]}')",
        "    print()",
    ),
    md("## Quick sanity check on the local metric"),
    code(
        "from src.metric import is_correct, extract_answer, score",
        "",
        "examples = [",
        "    ('The result is therefore \\\\boxed{42}.', '42', True),",
        "    ('I think the answer might be 41.999, so \\\\boxed{42.005}', '42', True),  # within 1e-2 rel tol",
        "    ('\\\\boxed{wrong}', 'right', False),",
        "    ('No box, just an answer of 7', '7', True),  # fallback to last number",
        "]",
        "for text, target, expected in examples:",
        "    got = is_correct(text, target)",
        "    print(f'extract={extract_answer(text)!r:>15}  target={target!r:>10}  ok={got}  expected={expected}')",
    ),
])


# -----------------------------------------------------------------------------
# 02_train_kaggle.ipynb — adapted from the official submission demo
# -----------------------------------------------------------------------------
train_nb = nb(accelerator="nvidiaRtxPro6000Blackwell", cells=[
    md(
        "# 02 · Train LoRA on Nemotron-3-Nano-30B (Kaggle GPU)",
        "",
        "Upload this notebook to Kaggle, attach the competition dataset and the",
        "`metric/nemotron-3-nano-30b-a3b-bf16` model, then run top to bottom.",
        "",
        "Output: `/kaggle/working/submission.zip` containing the LoRA adapter.",
    ),
    md(
        "## 0. Environment",
        "",
        "This kernel runs **offline** (Internet is blocked for non-T4 accelerators in",
        "this competition). Dependencies come from two attached Kaggle Datasets:",
        "  * `aditya2909rb/nemotron-native-wheels` — pre-built wheels for cp312:",
        "    `mamba_ssm-2.3.1`, `causal_conv1d-1.6.1`, `triton-3.6.0`, `einops-0.8.2`,",
        "    `bitsandbytes-0.49.2` (we don't actually use bnb on RTX Pro 6000).",
        "  * Kaggle base image already ships `torch`, `transformers`, `peft`,",
        "    `accelerate`, `trl`, `datasets`, `polars`.",
        "",
        "**Required GPU**: **GPU RTX Pro 6000** (95 GiB). Set via Kaggle UI; the CLI",
        "doesn't expose this accelerator option.",
    ),
    code(
        "# Step 0a: install mamba_ssm + causal_conv1d (and their wheel-set deps) from the",
        "# offline wheel cache. --no-deps avoids pulling stable versions that conflict",
        "# with Kaggle's base torch.",
        "import glob, subprocess, sys",
        "_wheels_dir = next(iter(glob.glob('/kaggle/input/nemotron-native-wheels')), None)",
        "if _wheels_dir is None:",
        "    raise RuntimeError(",
        "        'aditya2909rb/nemotron-native-wheels not attached. Add it via Kaggle UI -> Input -> '",
        "        'Add Input -> search aditya2909rb/nemotron-native-wheels -> Add.'",
        "    )",
        "print(f'wheels dir: {_wheels_dir}')",
        "print('contents:', sorted(p.split(\"/\")[-1] for p in glob.glob(_wheels_dir + '/*.whl')))",
        "",
        "_pip_cmd = [sys.executable, '-m', 'pip', 'install', '--no-index', '--no-deps',",
        "            '--find-links', _wheels_dir, 'einops', 'mamba_ssm', 'causal_conv1d']",
        "print('running:', ' '.join(_pip_cmd))",
        "subprocess.run(_pip_cmd, check=True)",
    ),
    code(
        "# Step 0b: probe all required imports. Raise immediately if anything's missing",
        "# so we fail fast and don't burn GPU time on a doomed run.",
        "import importlib",
        "_required = ['torch', 'transformers', 'peft', 'accelerate', 'trl', 'datasets',",
        "             'polars', 'einops', 'mamba_ssm', 'causal_conv1d']",
        "_missing = []",
        "for mod in _required:",
        "    try:",
        "        m = importlib.import_module(mod)",
        "        print(f'  OK: {mod:18s} {getattr(m, \"__version__\", \"?\"):10s} from {getattr(m, \"__file__\", \"?\")}')",
        "    except Exception as e:",
        "        _missing.append((mod, type(e).__name__, str(e)[:160]))",
        "        print(f'  FAIL: {mod:18s} {type(e).__name__}: {e}')",
        "if _missing:",
        "    raise RuntimeError(f'missing required packages: {[m[0] for m in _missing]}')",
    ),
    md(
        "## 1. Load the prebuilt SFT dataset",
        "",
        "Expects a Kaggle Dataset attached to the notebook containing `sft_v1.parquet`",
        "(produced locally via `scripts/build_sft_data.py`). The mount point varies by",
        "platform/CLI version, so we glob a few candidates instead of hard-coding one.",
    ),
    code(
        "import glob, json, os",
        "import polars as pl",
        "from datasets import Dataset",
        "",
        "_candidates = sorted(set(",
        "    glob.glob('/kaggle/input/wonderland-sft-v1/sft_v1.parquet')",
        "    + glob.glob('/kaggle/input/datasets/*/wonderland-sft-v1/sft_v1.parquet')",
        "    + glob.glob('/kaggle/input/*/sft_v1.parquet')",
        "))",
        "assert _candidates, 'sft_v1.parquet not found under /kaggle/input — attach the wonderland-sft-v1 dataset'",
        "SFT_PATH = _candidates[0]",
        "print('using SFT data at', SFT_PATH)",
        "",
        "df = pl.read_parquet(SFT_PATH)",
        "print('total rows:', df.height)",
        "print(df.group_by(['category', 'source']).agg(pl.len().alias('n')).sort(['category', 'source']))",
    ),
    md(
        "## 2. Stratified 90/10 train/val split",
        "",
        "Hold out ~10% of every category for offline scoring after training so we can",
        "spot-check the adapter before submitting. The split is deterministic",
        "(`seed=0`) and stratified — each category contributes ~10% of its rows to val.",
    ),
    code(
        "SPLIT_SEED = 0",
        "VAL_FRACTION = 0.10",
        "",
        "df = df.with_row_index('_row')",
        "val_parts, train_parts = [], []",
        "for cat in sorted(df['category'].unique().to_list()):",
        "    sub = df.filter(pl.col('category') == cat).sample(",
        "        fraction=1.0, shuffle=True, seed=SPLIT_SEED",
        "    )",
        "    n_val = max(1, int(round(sub.height * VAL_FRACTION)))",
        "    val_parts.append(sub.head(n_val))",
        "    train_parts.append(sub.tail(sub.height - n_val))",
        "",
        "df_val = pl.concat(val_parts).sort('_row').drop('_row')",
        "df_train = pl.concat(train_parts).sort('_row').drop('_row')",
        "df = df.drop('_row')",
        "",
        "print(f'train rows: {df_train.height}')",
        "print(f'val rows:   {df_val.height}')",
        "print('val per-category:')",
        "print(df_val.group_by('category').agg(pl.len().alias('n')).sort('category'))",
    ),
    md("## 3. Build the HuggingFace Dataset (messages format)"),
    code(
        "rows = [{'messages': json.loads(m)} for m in df_train['messages'].to_list()]",
        "ds = Dataset.from_list(rows)",
        "print(ds)",
        "print('example messages:')",
        "for m in ds[0]['messages']:",
        "    print(f\"[{m['role']}]\", m['content'][:200])",
    ),
    md(
        "## 4. Load Nemotron-3-Nano-30B + attach LoRA (BF16)",
        "",
        "RTX Pro 6000 Blackwell ships with 95 GiB VRAM — the full 30B model in BF16",
        "(~60 GB) fits comfortably alongside activations, LoRA gradients, and AdamW",
        "optimiser state. We skip bitsandbytes 4-bit quantization entirely (which",
        "isn't in the base image and isn't shipped by the utility-script) and load",
        "the weights directly in BF16. The grader uses BF16 inference anyway, so",
        "this matches the eval path more faithfully than QLoRA would.",
    ),
    code(
        "import site, subprocess",
        "import torch",
        "",
        "# Diagnostics: surface the allocated accelerator BEFORE we try to load a 30B model.",
        "print(f'torch.cuda.is_available(): {torch.cuda.is_available()}')",
        "print(f'torch.cuda.device_count(): {torch.cuda.device_count()}')",
        "_total_vram_gib = 0.0",
        "for i in range(torch.cuda.device_count()):",
        "    props = torch.cuda.get_device_properties(i)",
        "    print(f'  cuda:{i}  {torch.cuda.get_device_name(i)}  '",
        "          f'{props.total_memory / 1024**3:.1f} GiB  sm_{props.major}{props.minor}')",
        "    _total_vram_gib += props.total_memory / 1024**3",
        "print(f'total VRAM: {_total_vram_gib:.1f} GiB')",
        "print()",
        "if _total_vram_gib < 28:  # 30B in 4-bit (~15 GiB) + activations + LoRA needs ~25+",
        "    raise RuntimeError(",
        "        f'Total VRAM is only {_total_vram_gib:.1f} GiB. Need >= 28 GiB across all GPUs. '",
        "        'Settings -> Accelerator -> GPU RTX Pro 6000 (48 GiB) or GPU T4 x2 (32 GiB).'",
        "    )",
        "print(subprocess.run(['nvidia-smi'], capture_output=True, text=True).stdout)",
        "",
        "# mamba_ssm + causal_conv1d already installed by cell 0a from the wheels dataset;",
        "# no extra path manipulation needed here.",
        "",
        "import kagglehub",
        "from peft import LoraConfig, get_peft_model, TaskType",
        "from transformers import AutoModelForCausalLM, AutoTokenizer",
        "",
        "MODEL_PATH = kagglehub.model_download('metric/nemotron-3-nano-30b-a3b-bf16/transformers/default')",
        "OUTPUT_DIR = '/kaggle/working'",
        "LORA_RANK = 32  # grader enforces max_lora_rank=32",
        "",
        "tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)",
        "if tokenizer.pad_token is None:",
        "    tokenizer.pad_token = tokenizer.eos_token",
        "",
        "os.environ.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')",
        "",
        "model = AutoModelForCausalLM.from_pretrained(",
        "    MODEL_PATH,",
        "    dtype=torch.bfloat16,",
        "    device_map='auto',",
        "    trust_remote_code=True,",
        "    low_cpu_mem_usage=True,",
        ")",
        "print('device map after load:')",
        "if hasattr(model, 'hf_device_map'):",
        "    for k, v in sorted(model.hf_device_map.items())[:20]:",
        "        print(f'  {k:60s} -> {v}')",
        "    print(f'  (total entries: {len(model.hf_device_map)})')",
        "",
        "# Manually enable gradient checkpointing without prepare_model_for_kbit_training",
        "# (that helper is only needed for k-bit quantized loads, which we no longer do).",
        "model.gradient_checkpointing_enable()",
        "model.enable_input_require_grads()",
        "",
        "lora_config = LoraConfig(",
        "    r=LORA_RANK,",
        "    lora_alpha=16,",
        "    target_modules=r'.*\\\\.(in_proj|out_proj|up_proj|down_proj)$',",
        "    lora_dropout=0.05,",
        "    bias='none',",
        "    task_type=TaskType.CAUSAL_LM,",
        ")",
        "model = get_peft_model(model, lora_config)",
        "model.print_trainable_parameters()",
    ),
    md(
        "## 5. SFT training",
        "",
        "Single-epoch SFT with TRL. Tune batch size / grad-accum / LR to fit your GPU.",
        "On L4 x4 the values below are a reasonable starting point; on T4 x2 drop",
        "`per_device_train_batch_size` to 1 and add 4-bit base loading.",
    ),
    code(
        "from trl import SFTTrainer, SFTConfig",
        "",
        "cfg = SFTConfig(",
        "    output_dir=OUTPUT_DIR,",
        "    per_device_train_batch_size=1,",
        "    gradient_accumulation_steps=16,",
        "    num_train_epochs=1,",
        "    learning_rate=2e-4,",
        "    bf16=True,",
        "    logging_steps=25,",
        "    save_strategy='no',",
        "    max_seq_length=2048,",
        "    packing=False,",
        ")",
        "",
        "trainer = SFTTrainer(",
        "    model=model,",
        "    args=cfg,",
        "    train_dataset=ds,",
        "    tokenizer=tokenizer,",
        ")",
        "trainer.train()",
    ),
    md(
        "## 6. Held-out validation",
        "",
        "Run inference on the held-out split and score it locally with the same rule",
        "the grader uses (last `\\boxed{...}` → fallback to last number → exact-match or",
        "rel-tol ≤ 1e-2). Edit `VAL_CAP` to trade off wall time vs. signal — we cap to",
        "~300 rows by default sampled uniformly across categories.",
        "",
        "Generation params mirror the grader: `do_sample=False`, `temperature=0.0`,",
        "`max_new_tokens=7680`. We prefer vLLM with the trained LoRA loaded as a",
        "request-time adapter; if vLLM can't initialise in the Kaggle env (e.g. no",
        "wheel for the Mamba kernels), we fall back to `model.generate` in small",
        "batches with the same params.",
    ),
    md("### 6a. Validation config + prompt construction"),
    code(
        "VAL_CAP = 300  # set to None to score the entire val split (slow!)",
        "VAL_BATCH_SIZE = 4  # only used by the transformers fallback",
        "",
        "# Save the LoRA adapter to disk first so vLLM can load it from a path.",
        "ADAPTER_DIR = OUTPUT_DIR + '/adapter_for_val'",
        "model.save_pretrained(ADAPTER_DIR)",
        "print('saved adapter to', ADAPTER_DIR)",
        "",
        "# Uniformly cap val across categories (preserves stratification).",
        "if VAL_CAP is not None and df_val.height > VAL_CAP:",
        "    cats = sorted(df_val['category'].unique().to_list())",
        "    per_cat = max(1, VAL_CAP // len(cats))",
        "    capped = []",
        "    for cat in cats:",
        "        sub = df_val.filter(pl.col('category') == cat).sample(",
        "            fraction=1.0, shuffle=True, seed=SPLIT_SEED",
        "        )",
        "        capped.append(sub.head(per_cat))",
        "    df_val_eval = pl.concat(capped)",
        "else:",
        "    df_val_eval = df_val",
        "",
        "print(f'scoring {df_val_eval.height} val rows')",
        "print(df_val_eval.group_by('category').agg(pl.len().alias('n')).sort('category'))",
        "",
        "# For inference the assistant turn is what the model must produce; use only",
        "# [system, user] and let chat-template add the assistant-start marker.",
        "val_records = []",
        "for row in df_val_eval.iter_rows(named=True):",
        "    msgs = json.loads(row['messages'])",
        "    inference_msgs = [m for m in msgs if m['role'] != 'assistant']",
        "    prompt_text = tokenizer.apply_chat_template(",
        "        inference_msgs, tokenize=False, add_generation_prompt=True",
        "    )",
        "    val_records.append({",
        "        'id': row['id'],",
        "        'category': row['category'],",
        "        'prompt_text': prompt_text,",
        "        'target': row['answer'],",
        "    })",
        "",
        "print(f'built {len(val_records)} prompts; first prompt tail:')",
        "print('...' + val_records[0]['prompt_text'][-300:])",
    ),
    md(
        "### 6b. Local metric (mirrors the grader)",
        "",
        "Re-implemented inline so this notebook stays self-contained — the Kaggle",
        "runtime doesn't have our repo.",
    ),
    code(
        "import re",
        "",
        "_BOXED_RE = re.compile(r'\\\\boxed\\{(.*?)\\}', re.DOTALL)",
        "_NUM_RE = re.compile(r'-?\\d+(?:\\.\\d+)?(?:[eE][-+]?\\d+)?')",
        "REL_TOL = 1e-2",
        "",
        "def extract_answer(text: str) -> str:",
        "    boxed = _BOXED_RE.findall(text)",
        "    if boxed:",
        "        return boxed[-1].strip()",
        "    nums = _NUM_RE.findall(text)",
        "    if nums:",
        "        return nums[-1]",
        "    return text.strip()",
        "",
        "def _try_float(s: str):",
        "    try:",
        "        return float(s)",
        "    except (ValueError, TypeError):",
        "        return None",
        "",
        "def is_correct(prediction: str, target: str) -> bool:",
        "    pred = extract_answer(prediction).strip()",
        "    tgt = target.strip()",
        "    if pred == tgt:",
        "        return True",
        "    p_num, t_num = _try_float(pred), _try_float(tgt)",
        "    if p_num is not None and t_num is not None:",
        "        if t_num == 0.0:",
        "            return abs(p_num) <= REL_TOL",
        "        return abs(p_num - t_num) / abs(t_num) <= REL_TOL",
        "    return False",
        "",
        "# Quick self-test so a regression in the regex shows up immediately.",
        "assert extract_answer('the answer is \\\\boxed{42}') == '42'",
        "assert is_correct('\\\\boxed{42.005}', '42')  # within rel-tol",
        "assert not is_correct('\\\\boxed{nope}', 'yes')",
        "assert is_correct('I get 7 then 13', '13')  # last-number fallback",
        "print('metric self-test ok')",
    ),
    md(
        "### 6c. Run inference (vLLM preferred, transformers fallback)",
        "",
        "vLLM matches the grader exactly. If it can't be imported / initialised in this",
        "environment we drop to plain `model.generate` with the same params — slower but",
        "always available.",
    ),
    code(
        "predictions = [None] * len(val_records)",
        "inference_backend = None",
        "",
        "try:",
        "    from vllm import LLM, SamplingParams",
        "    from vllm.lora.request import LoRARequest",
        "",
        "    print('attempting vLLM inference...')",
        "    # Free GPU memory held by the training model + optimiser before booting vLLM.",
        "    import gc",
        "    del trainer",
        "    gc.collect()",
        "    torch.cuda.empty_cache()",
        "",
        "    llm = LLM(",
        "        model=MODEL_PATH,",
        "        dtype='bfloat16',",
        "        trust_remote_code=True,",
        "        enable_lora=True,",
        "        max_lora_rank=LORA_RANK,",
        "        max_model_len=8192,",
        "        gpu_memory_utilization=0.85,",
        "    )",
        "    sampling = SamplingParams(temperature=0.0, top_p=1.0, max_tokens=7680)",
        "    lora_req = LoRARequest('trained_adapter', 1, ADAPTER_DIR)",
        "",
        "    prompts = [r['prompt_text'] for r in val_records]",
        "    outputs = llm.generate(prompts, sampling, lora_request=lora_req)",
        "    # `llm.generate` returns outputs in the same order as the input prompts.",
        "    for i, o in enumerate(outputs):",
        "        predictions[i] = o.outputs[0].text",
        "    inference_backend = 'vllm'",
        "    print('vLLM inference done')",
        "except Exception as e:",
        "    print(f'vLLM unavailable ({type(e).__name__}: {e}); falling back to transformers.generate')",
        "    inference_backend = 'transformers'",
        "",
        "if inference_backend == 'transformers':",
        "    model.eval()",
        "    for start in range(0, len(val_records), VAL_BATCH_SIZE):",
        "        batch = val_records[start:start + VAL_BATCH_SIZE]",
        "        enc = tokenizer(",
        "            [r['prompt_text'] for r in batch],",
        "            return_tensors='pt', padding=True, truncation=False,",
        "        ).to(model.device)",
        "        with torch.no_grad():",
        "            out_ids = model.generate(",
        "                **enc,",
        "                do_sample=False,",
        "                temperature=0.0,",
        "                top_p=1.0,",
        "                max_new_tokens=7680,",
        "                pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,",
        "            )",
        "        for i, ids in enumerate(out_ids):",
        "            prompt_len = enc['input_ids'][i].shape[0]",
        "            gen_ids = ids[prompt_len:]",
        "            predictions[start + i] = tokenizer.decode(gen_ids, skip_special_tokens=True)",
        "        print(f'  generated rows {start}..{start + len(batch) - 1}')",
        "",
        "print(f'inference backend: {inference_backend}')",
        "print(f'predictions filled: {sum(p is not None for p in predictions)} / {len(predictions)}')",
    ),
    md("### 6d. Per-category accuracy"),
    code(
        "scored = []",
        "for rec, pred in zip(val_records, predictions):",
        "    pred = pred or ''",
        "    scored.append({",
        "        'id': rec['id'],",
        "        'category': rec['category'],",
        "        'target': rec['target'],",
        "        'prediction': pred,",
        "        'extracted': extract_answer(pred),",
        "        'correct': is_correct(pred, rec['target']),",
        "    })",
        "",
        "scored_df = pl.DataFrame(scored)",
        "overall_acc = scored_df['correct'].mean()",
        "",
        "per_cat = scored_df.group_by('category').agg([",
        "    pl.len().alias('n'),",
        "    pl.col('correct').mean().alias('accuracy'),",
        "]).sort('category')",
        "",
        "print(f'overall val accuracy: {overall_acc:.4f} ({scored_df[\"correct\"].sum()}/{scored_df.height})')",
        "print(per_cat)",
    ),
    md("### 6e. Debug printouts — one example per category"),
    code(
        "for cat in sorted(scored_df['category'].unique().to_list()):",
        "    ex = scored_df.filter(pl.col('category') == cat).head(1).to_dicts()[0]",
        "    rec = next(r for r in val_records if r['id'] == ex['id'])",
        "    print('=' * 80)",
        "    print(f\"CATEGORY: {cat}   id={ex['id']}   correct={ex['correct']}\")",
        "    print('=' * 80)",
        "    print('PROMPT (last 200 chars):')",
        "    print('...' + rec['prompt_text'][-200:])",
        "    print()",
        "    print('GENERATED:')",
        "    print(ex['prediction'])",
        "    print()",
        "    print(f\"TRUE ANSWER:  {ex['target']}\")",
        "    print(f\"EXTRACTED:    {ex['extracted']}\")",
        "    print()",
    ),
    md("### 6f. Low-accuracy banner"),
    code(
        "if overall_acc < 0.30:",
        "    banner = (",
        "        '\\n' + '!' * 78 + '\\n'",
        "        '!! VAL ACC LOW — review before submitting' + ' ' * 33 + '!!\\n'",
        "        '!! overall = ' + f'{overall_acc:.4f}' + ' (threshold 0.30)' + ' ' * 38 + '!!\\n'",
        "        '!! likely causes: under-trained adapter, broken chat template, format drift !!\\n'",
        "        '!! inspect the per-category table + debug printouts above before proceeding !!\\n'",
        "        + '!' * 78 + '\\n'",
        "    )",
        "    print(banner)",
        "else:",
        "    print(f'val acc {overall_acc:.4f} >= 0.30 — proceeding to package submission')",
    ),
    md("## 7. Save adapter and package submission.zip"),
    code(
        "model.save_pretrained(OUTPUT_DIR)",
        "import os, subprocess",
        "os.chdir(OUTPUT_DIR)",
        "subprocess.run('zip -m submission.zip adapter_config.json adapter_model.safetensors', shell=True, check=True)",
        "print('Wrote /kaggle/working/submission.zip')",
    ),
])


def write_nb(name: str, data: dict) -> None:
    out = NB_DIR / name
    out.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n")
    print(f"wrote {out.relative_to(REPO)}  ({out.stat().st_size} bytes)")


# -----------------------------------------------------------------------------
# 03_train_colab.ipynb — Colab Pro variant (internet ON, simpler setup)
# -----------------------------------------------------------------------------
colab_nb = nb([
    md(
        "# 03 · Train LoRA on Nemotron-3-Nano-30B (Google Colab Pro)",
        "",
        "**Open this in Colab** via File → Upload, or via the Colab badge in the repo.",
        "",
        "Requirements:",
        "  * Colab Pro (or Pro+) with **A100 40 GB** or **L4 24 GB** runtime.",
        "  * Kaggle API token added to Colab Secrets (left sidebar 🗝):",
        "    * `KAGGLE_USERNAME` = your Kaggle username (e.g. `jokerdc`)",
        "    * `KAGGLE_KEY`      = your Kaggle API key (the new short token works too)",
        "  * Public Kaggle dataset `<you>/wonderland-sft-v1` already exists.",
        "",
        "What this notebook does:",
        "  1. Install deps (PEFT, TRL, datasets, bitsandbytes, mamba-ssm, causal-conv1d).",
        "  2. Auth to Kaggle from Secrets.",
        "  3. Download SFT data + Nemotron-3-Nano-30B base model via kagglehub.",
        "  4. QLoRA fine-tune (4-bit base + LoRA rank 32). Auto-picks BF16 if GPU has ≥ 70 GB.",
        "  5. Run held-out validation on 300 rows with the same metric the grader uses.",
        "  6. Save the adapter and pack `submission.zip` for download.",
    ),
    md("## 0. GPU check"),
    code(
        "import subprocess, torch",
        "print(f'torch.cuda.is_available(): {torch.cuda.is_available()}')",
        "print(f'torch.cuda.device_count(): {torch.cuda.device_count()}')",
        "for i in range(torch.cuda.device_count()):",
        "    props = torch.cuda.get_device_properties(i)",
        "    print(f'  cuda:{i}  {torch.cuda.get_device_name(i)}  '",
        "          f'{props.total_memory / 1024**3:.1f} GiB  sm_{props.major}{props.minor}')",
        "print(subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader'],",
        "                     capture_output=True, text=True).stdout)",
    ),
    md(
        "## 1. Install dependencies",
        "",
        "Colab has internet, so this is the standard pip install path. `mamba-ssm` and",
        "`causal-conv1d` are compiled extensions; using the maintainer's hosted wheels",
        "avoids the slow build-from-source path.",
    ),
    code(
        "%pip install -q -U peft accelerate trl datasets bitsandbytes polars huggingface-hub kagglehub",
        "# Mamba kernels — pin to known-good versions matching Colab's torch 2.5/2.6 + cu12.",
        "%pip install -q --no-build-isolation mamba-ssm==2.3.1 causal-conv1d==1.6.1 einops",
    ),
    md(
        "## 2. Kaggle auth via Colab Secrets",
        "",
        "Open the 🗝 panel on the left, add `KAGGLE_USERNAME` and `KAGGLE_KEY` as Secrets",
        "with notebook access enabled, then run this cell. Falls back to a manual paste",
        "if Secrets aren't set.",
    ),
    code(
        "import os, json, getpass",
        "try:",
        "    from google.colab import userdata",
        "    os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')",
        "    os.environ['KAGGLE_KEY']      = userdata.get('KAGGLE_KEY')",
        "    print('loaded Kaggle creds from Colab Secrets')",
        "except Exception as e:",
        "    print(f'Colab Secrets unavailable ({e}); falling back to manual entry')",
        "    if 'KAGGLE_USERNAME' not in os.environ:",
        "        os.environ['KAGGLE_USERNAME'] = input('Kaggle username: ').strip()",
        "    if 'KAGGLE_KEY' not in os.environ:",
        "        os.environ['KAGGLE_KEY'] = getpass.getpass('Kaggle key: ').strip()",
        "",
        "# Also drop a ~/.kaggle/kaggle.json so kagglehub / kaggle CLI both find it.",
        "kdir = os.path.expanduser('~/.kaggle')",
        "os.makedirs(kdir, exist_ok=True)",
        "with open(f'{kdir}/kaggle.json', 'w') as f:",
        "    json.dump({'username': os.environ['KAGGLE_USERNAME'], 'key': os.environ['KAGGLE_KEY']}, f)",
        "os.chmod(f'{kdir}/kaggle.json', 0o600)",
        "print('kaggle.json written for', os.environ['KAGGLE_USERNAME'])",
    ),
    md("## 3. Download SFT data + base model"),
    code(
        "import kagglehub",
        "import polars as pl",
        "",
        "# SFT data — the dataset we prepared locally.",
        "SFT_USER = os.environ['KAGGLE_USERNAME']",
        "SFT_DIR = kagglehub.dataset_download(f'{SFT_USER}/wonderland-sft-v1')",
        "print('SFT dir:', SFT_DIR)",
        "",
        "import glob",
        "SFT_PATH = next(iter(glob.glob(f'{SFT_DIR}/**/sft_v1.parquet', recursive=True)))",
        "df = pl.read_parquet(SFT_PATH)",
        "print('total rows:', df.height)",
        "print(df.group_by(['category', 'source']).agg(pl.len().alias('n')).sort(['category', 'source']))",
        "",
        "# Base model — large (~63 GiB); progress bar will appear.",
        "MODEL_PATH = kagglehub.model_download('metric/nemotron-3-nano-30b-a3b-bf16/transformers/default')",
        "print('model dir:', MODEL_PATH)",
    ),
    md(
        "## 4. Stratified 90/10 train/val split + HF Dataset",
    ),
    code(
        "import json",
        "from datasets import Dataset",
        "",
        "SPLIT_SEED = 0",
        "VAL_FRACTION = 0.10",
        "",
        "df = df.with_row_index('_row')",
        "val_parts, train_parts = [], []",
        "for cat in sorted(df['category'].unique().to_list()):",
        "    sub = df.filter(pl.col('category') == cat).sample(fraction=1.0, shuffle=True, seed=SPLIT_SEED)",
        "    n_val = max(1, int(round(sub.height * VAL_FRACTION)))",
        "    val_parts.append(sub.head(n_val))",
        "    train_parts.append(sub.tail(sub.height - n_val))",
        "df_val = pl.concat(val_parts).sort('_row').drop('_row')",
        "df_train = pl.concat(train_parts).sort('_row').drop('_row')",
        "df = df.drop('_row')",
        "print(f'train rows: {df_train.height}   val rows: {df_val.height}')",
        "",
        "ds_train = Dataset.from_list([{'messages': json.loads(m)} for m in df_train['messages'].to_list()])",
        "print(ds_train)",
    ),
    md(
        "## 5. Load model — QLoRA on A100/L4, BF16 if you have ≥ 70 GiB",
    ),
    code(
        "import torch",
        "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType",
        "from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig",
        "",
        "OUTPUT_DIR = '/content/outputs'",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)",
        "LORA_RANK = 32",
        "",
        "vram_gib = torch.cuda.get_device_properties(0).total_memory / 1024**3",
        "use_4bit = vram_gib < 70",
        "print(f'VRAM={vram_gib:.1f} GiB → load_strategy={\"4-bit QLoRA\" if use_4bit else \"BF16\"}')",
        "",
        "tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)",
        "if tokenizer.pad_token is None:",
        "    tokenizer.pad_token = tokenizer.eos_token",
        "",
        "os.environ.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')",
        "",
        "load_kwargs = dict(",
        "    device_map='auto',",
        "    trust_remote_code=True,",
        "    low_cpu_mem_usage=True,",
        ")",
        "if use_4bit:",
        "    load_kwargs['quantization_config'] = BitsAndBytesConfig(",
        "        load_in_4bit=True,",
        "        bnb_4bit_quant_type='nf4',",
        "        bnb_4bit_compute_dtype=torch.bfloat16,",
        "        bnb_4bit_use_double_quant=True,",
        "    )",
        "else:",
        "    load_kwargs['dtype'] = torch.bfloat16",
        "",
        "model = AutoModelForCausalLM.from_pretrained(MODEL_PATH, **load_kwargs)",
        "if use_4bit:",
        "    model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)",
        "else:",
        "    model.gradient_checkpointing_enable()",
        "    model.enable_input_require_grads()",
        "",
        "lora_config = LoraConfig(",
        "    r=LORA_RANK, lora_alpha=16,",
        "    target_modules=r'.*\\\\.(in_proj|out_proj|up_proj|down_proj)$',",
        "    lora_dropout=0.05, bias='none', task_type=TaskType.CAUSAL_LM,",
        ")",
        "model = get_peft_model(model, lora_config)",
        "model.print_trainable_parameters()",
    ),
    md("## 6. SFT training"),
    code(
        "from trl import SFTTrainer, SFTConfig",
        "",
        "cfg = SFTConfig(",
        "    output_dir=OUTPUT_DIR,",
        "    per_device_train_batch_size=1,",
        "    gradient_accumulation_steps=16,",
        "    num_train_epochs=1,",
        "    learning_rate=2e-4,",
        "    bf16=True,",
        "    logging_steps=25,",
        "    save_strategy='no',",
        "    max_seq_length=2048,",
        "    packing=False,",
        ")",
        "trainer = SFTTrainer(model=model, args=cfg, train_dataset=ds_train, tokenizer=tokenizer)",
        "trainer.train()",
    ),
    md(
        "## 7. Held-out validation (sample of 300 rows)",
        "",
        "Inline copy of the local metric so the notebook stays self-contained.",
    ),
    code(
        "import re",
        "",
        "VAL_CAP = 300",
        "ADAPTER_DIR = OUTPUT_DIR + '/adapter'",
        "model.save_pretrained(ADAPTER_DIR)",
        "",
        "cats = sorted(df_val['category'].unique().to_list())",
        "per_cat = max(1, VAL_CAP // len(cats))",
        "df_val_eval = pl.concat([",
        "    df_val.filter(pl.col('category') == c).sample(fraction=1.0, shuffle=True, seed=SPLIT_SEED).head(per_cat)",
        "    for c in cats",
        "])",
        "print(f'scoring {df_val_eval.height} rows')",
        "",
        "_BOXED_RE = re.compile(r'\\\\boxed\\{(.*?)\\}', re.DOTALL)",
        "_NUM_RE = re.compile(r'-?\\d+(?:\\.\\d+)?(?:[eE][-+]?\\d+)?')",
        "def extract_answer(text):",
        "    boxed = _BOXED_RE.findall(text)",
        "    if boxed: return boxed[-1].strip()",
        "    nums = _NUM_RE.findall(text)",
        "    if nums: return nums[-1]",
        "    return text.strip()",
        "def _f(s):",
        "    try: return float(s)",
        "    except: return None",
        "def is_correct(pred, target):",
        "    p = extract_answer(pred).strip(); t = target.strip()",
        "    if p == t: return True",
        "    pn, tn = _f(p), _f(t)",
        "    if pn is None or tn is None: return False",
        "    return abs(pn - tn) / max(abs(tn), 1e-12) <= 1e-2",
        "",
        "model.eval()",
        "scored = []",
        "for row in df_val_eval.iter_rows(named=True):",
        "    msgs = json.loads(row['messages'])",
        "    inf_msgs = [m for m in msgs if m['role'] != 'assistant']",
        "    text = tokenizer.apply_chat_template(inf_msgs, tokenize=False, add_generation_prompt=True)",
        "    ids = tokenizer(text, return_tensors='pt').to(model.device)",
        "    with torch.no_grad():",
        "        out = model.generate(**ids, do_sample=False, max_new_tokens=2048,",
        "                              pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id)",
        "    gen = tokenizer.decode(out[0, ids['input_ids'].shape[1]:], skip_special_tokens=True)",
        "    scored.append({'category': row['category'], 'target': row['answer'],",
        "                   'prediction': gen, 'correct': is_correct(gen, row['answer'])})",
        "",
        "scored_df = pl.DataFrame(scored)",
        "print(f'overall val acc: {scored_df[\"correct\"].mean():.4f}')",
        "print(scored_df.group_by('category').agg([",
        "    pl.len().alias('n'), pl.col('correct').mean().alias('acc')",
        "]).sort('category'))",
    ),
    md("## 8. Package submission.zip + download"),
    code(
        "import shutil",
        "shutil.make_archive(OUTPUT_DIR + '/submission', 'zip', ADAPTER_DIR)",
        "print('wrote', OUTPUT_DIR + '/submission.zip',",
        "      f'({os.path.getsize(OUTPUT_DIR + \"/submission.zip\")/1024/1024:.2f} MB)')",
        "",
        "# Download to your local machine.",
        "from google.colab import files",
        "files.download(OUTPUT_DIR + '/submission.zip')",
    ),
])


if __name__ == "__main__":
    write_nb("01_eda.ipynb", eda)
    write_nb("02_train_kaggle.ipynb", train_nb)
    write_nb("03_train_colab.ipynb", colab_nb)
